<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>WoSe</AssemblyName>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PlatformTarget>x64</PlatformTarget>
		<PublishReadyToRun>false</PublishReadyToRun>
		<RootNamespace>Wose.Desktop</RootNamespace>
		<SatelliteResourceLanguages>en;cs-CZ</SatelliteResourceLanguages>
		<ApplicationIcon>WordSearchGenerator.Desktop.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CefSharp.Wpf.NETCore" Version="150.0.110" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
		<PackageReference Include="FluentIcons.Wpf" Version="2.1.335" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WordSearchGenerator.Common\WordSearchGenerator.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\BoardStyles\*.css" />
		<Resource Include="WordSearchGenerator.Desktop.ico" />
	</ItemGroup>

</Project>
