<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>WoSe.Tests</AssemblyName>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Wose.Tests</RootNamespace>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
		<PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
		<PackageReference Include="coverlet.collector" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WordSearchGenerator.Common\WordSearchGenerator.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\..\test-data\memorial.txt"
		         Link="test-data\memorial.txt"
		         CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
